### ISSUE TITLE
GNOME 3.22 support

### ISSUE THREAD

**Issue by iliaross** [kusabashira/short-memo#2]
Hi,

Thank you for your extension. Are you planning to add GNOME 3.22 support?

**Comment by nil-two** [comment]
Sorry. I just uploaded now to support GNOME 3.22.
It will be available as soon as it passes reviewing.

Thank you for using my extension!
Now I cannot add functions because there is no energy,
but I will continue to support the new versions.

**Comment by iliaross** [comment]
Thank you!

To get energy, just sleep more and take less caffeine.
